### ISSUE TITLE
Add 'since' and/or 'forRemoval' arguments to the @Depracated annotation

### ISSUE THREAD

**Issue by mehtavandit** [dneha1210/OpenTracks-Winter-SOEN-6431_2024-Group8#3]
Adding 'since' and/or 'forRemoval' arguments to the @Deprecated annotation to developers about when the deprecated feature was introduced and when it's planned to be removed. This aids in understanding the deprecation timeline, guiding developers to update their code accordingly. It also serves as documentation for future maintainers, clarifying the deprecation process.

![WhatsApp Image 2024-02-12 at 15 18 26_09ec1611](https://github.com/dneha1210/OpenTracks-Winter-SOEN-6431_2024-Group8/assets/65803900/2aecaac1-2316-42e9-82cd-67b27aafc6e5)

**Comment by RushiDonga** [comment]
I've addressed the issue by adding 'since' and 'forRemoval' arguments to the @Deprecated annotation, providing clear information on the deprecation timeline. This helps developers understand when the feature was introduced and when it's planned to be removed, aiding in code maintenance and updates.

![Screenshot (48)](https://github.com/dneha1210/OpenTracks-Winter-SOEN-6431_2024-Group8/assets/65907580/ff9254d6-bcf5-489e-bcfd-24ef76bfc5a7)
